Aplicação CRUD com Django/livros/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'livros'

urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('<int:resenha_id>/', views.detail_resenha, name='detail'), 
    path('update/<int:resenha_id>/', views.update_resenha, name='update'), 
    path('delete/<int:resenha_id>/', views.delete_resenha, name='delete'), 
    path('search/', views.search_resenha, name='search'), 
    path('create/', views.create_resenha, name='create'), 
    path('<int:resenha_id>/createcomments/', views.create_comment, name='create_comment'), 
    path('<int:resenha_id>/comments/', views.view_comments, name='view_comments'), 
    
# Listagem de todas as categorias
    path('categories/', views.CategoryListView.as_view(), name='category_list'), 
    
    # Detalhe da categoria (lista posts da categoria)
    path('categories/<int:pk>/', views.category_detail, name='category_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Aplicação CRUD com Django/site_resenhas/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('livros/', include('livros.urls', namespace='livros')),
    path('', include('staticpages.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Aplicação CRUD com Django/livros/models.py
from django.db import models
from django.conf import settings
    

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name="Nome da Categoria")
    description = models.TextField(blank=True, verbose_name="Descrição")

    def __str__(self):
        return self.name
    
    # Adiciona a URL absoluta para a view de detalhes de categoria
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('livros:category_detail', kwargs={'pk': self.pk}) 
    
    class Meta:
        verbose_name_plural = "Categorias" # Correção gramatical para Admin
    


class Resenha(models.Model):
    title = models.CharField(max_length=200)
    data_postagem = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)

    autor_nome = models.TextField(max_length=500, null=True) 
    resenha = models.TextField() 
    
    image = models.ImageField(upload_to='category_images/', blank=True, null=True)

    categories = models.ManyToManyField(Category, related_name='resenhas')

    def __str__(self):
        return self.title
    

class Comment(models.Model):
    post = models.ForeignKey(Resenha, on_delete=models.CASCADE)
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.autor} - {self.text}'

Aplicação CRUD com Django/livros/forms.py
from django.forms import ModelForm
from .models import Resenha, Comment

class ResenhaForm(ModelForm):
    class Meta:
        model = Resenha
        fields = ['title', 'autor_nome', 'resenha', 'image']

        labels = {
            'title': 'Título do livro Resenhado',
            'autor_nome': 'Nome do Autor do livro',
            'resenha': 'Corpo da Resenha',
            'image': 'Capa/Imagem',
        }
        
class ReviewForm(ModelForm):
    class Meta:
        model = Comment
        fields = [ 'text']
        labels = {
            'text': 'Comentário',
        }

Aplicação CRUD com Django/livros/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import ResenhaForm, ReviewForm
from .models import Resenha, Comment, Category
from django.views import generic
from django.views.generic import ListView, DetailView


# CRUD
####################### READ ##################################

class IndexView(generic.ListView):
    model = Resenha
    # CORREÇÃO 1: Template path de 'resenhas/' para 'livros/'
    template_name = 'livros/index.html'


def detail_resenha(request, resenha_id):
    resenha = get_object_or_404(Resenha, pk=resenha_id)
    comments = Comment.objects.filter(post=resenha).order_by('-date')
    context = {'resenha': resenha,
               'comments': comments}
    # CORREÇÃO 1: Template path de 'resenhas/' para 'livros/'
    return render(request, 'livros/detail.html', context)
####################################################################

####################### SEARCH ##################################
def search_resenha(request):
    context = {"resenha_list": []}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        post_list = Resenha.objects.filter(title__icontains=search_term)
        context = {
            'resenha_list': post_list
        }
    return render(request, 'livros/search.html', context)
#####################################################################

####################### CREATE ##################################
def create_resenha(request):
    if request.method == 'POST':
        post_form = ResenhaForm(request.POST)
        if post_form.is_valid():
            post = Resenha(**post_form.cleaned_data)
            post.save()
            return HttpResponseRedirect(reverse('livros:detail', args=(post.pk,)))
    else: 
        post_form = ResenhaForm() 
    context = {'form': post_form}
    return render(request, 'livros/create.html', context)
#####################################################################

####################### UPDATE ##################################
def update_resenha(request, resenha_id):
    resenha = get_object_or_404(Resenha, pk=resenha_id)
    if request.method == 'POST':
        form = ResenhaForm(request.POST, request.FILES, instance=resenha)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('livros:detail', args=(resenha_id,)))
    else: 
        form = ResenhaForm(instance=resenha)
    context = {'resenha': resenha, 'form': form}
    return render(request, 'livros/update.html', context)
#####################################################################

####################### DELETE ##################################
def delete_resenha(request, resenha_id):
    post = get_object_or_404(Resenha, pk=resenha_id)
    if request.method == 'POST':
        post.delete()
        return HttpResponseRedirect(reverse('livros:index'))
    context = {'resenha': post}
    return render(request, 'livros/delete.html', context)
#####################################################################
def view_comments(request, resenha_id):
    resenha = get_object_or_404(Resenha, pk=resenha_id)
    comments = Comment.objects.filter(post=resenha).order_by('-date')
    context = {'resenha': resenha,
               'comments': comments}
    return render(request, 'livros/comments.html', context)

def create_comment(request, resenha_id):
    post = get_object_or_404(Resenha, pk=resenha_id)
    
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            
            if request.user.is_authenticated:
                comment_autor = request.user
            else:
                comment_autor = None 
                
            comment_text = form.cleaned_data['text']
            
            comment = Comment(post=post, autor=comment_autor, text=comment_text)
            comment.save()
            
            return HttpResponseRedirect(reverse('livros:detail', args=(resenha_id,)))
    
    else:
        form = ReviewForm()
        
    context = {'form': form, 'resenha': post}
    return render(request, 'livros/create_comment.html', context)
#############################################################################

class CategoryListView(ListView):
    model = Category
    template_name = 'livros/category_list.html'
    context_object_name = 'categories'

def category_detail(request, pk):
    category = get_object_or_404(Category, pk=pk) 

    resenha_list = category.resenhas.all().order_by('-data_postagem') 

    context = {
        'category': category,
        'resenha_list': resenha_list,
    }
    return render(request, 'livros/resenha_list.html', context)

Aplicação CRUD com Django/livros/templates/livros/category_detail.html
{% extends 'base.html' %}

{% block content %}
<h2>Resenhas na categoria: {{ categoria.name }}</h2>

{% if resenhas %}
    <ul>
    {% for resenha in resenhas %}
        <li>
            <a href="{% url 'livros:detail' resenha.id %}">
                {{ resenha.title }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>Nenhuma resenha encontrada nesta categoria.</p>
{% endif %}

<a href="{% url 'livros:categoria' %}">Voltar para a Lista de Categorias</a>
{% endblock content %}

Aplicação CRUD com Django/livros/templates/livros/category_list.html
{% extends 'base.html' %}

{% block content %}
    <h2>Todas as Categorias</h2>

    {% for category in categories %}
        <p>
            <a href="{% url 'livros:category_detail' category.pk %}">
                {{ category.name }} ({{ category.resenhas.count }} Resenhas)
            </a>
            <br>{{ category.description }}
        </p>
        <hr>
    {% empty %}
        <p>Nenhuma categoria cadastrada.</p>
    {% endfor %}
{% endblock content %}

Aplicação CRUD com Django/livros/templates/livros/comments.html
{% extends 'base.html'%}

{% block content %}
<h2> Comentários sobre a resenha "{{resenha.title}}"</h2>
{% for c in comments %}
    <p><b>{{ c.autor }} - {{ c.date|date:"d/m/Y H:i" }}:</b></p>
    <p>{{ c.text }}</p>
    <hr>
{% empty %}
    <p>Sem comentários ainda.</p>
{% endfor %}

<a href="{% url 'livros:create_comment' resenha.id %}">
    <button>Adicionar comentário</button>
</a>

<a href="{% url 'livros:detail' resenha.id %}">
    <button>Voltar para a resenha</button>
</a>
{% endblock %}

Aplicação CRUD com Django/livros/templates/livros/create.html
{% extends 'base.html'%}

{% block content %}
<h2> Criar nova resenha:</h2>
<form method="post" action = "{% url 'livros:create'%}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar Resenha</button>
</form>
{% endblock content %}

Aplicação CRUD com Django/livros/templates/livros/create_comment.html
{% extends 'base.html' %}

{% block title %} 
    Adicionar comentário à resenha "{{resenha.title}}"
{% endblock title %}

{% block content %}
<form method="post" action = "{% url 'livros:create_comment' resenha.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar comentário</button>
</form>

{# Opcional: Adicionar um link de voltar para a resenha #}
<p><a href="{% url 'livros:detail' resenha.id %}">Voltar para a resenha</a></p>
{% endblock content %}

Aplicação CRUD com Django/livros/templates/livros/delete.html
{% extends 'base.html'%}

{% block content %}
<h2> Deletar resenha "{{resenha.title}}"</h2>
<form method="post" action = "{% url 'livros:delete' resenha.id %}">
    {% csrf_token %}
    <p> Tem certeza que deseja deletar a resenha **"{{ resenha.title }}"**?</p>
    <button type="submit">Deletar Resenha</button>
    <a href="{% url 'livros:index' %}" class="btn">Voltar</a>
</form>
{% endblock content %}

Aplicação CRUD com Django/livros/templates/livros/detail.html
{% extends 'base.html'%}

{% block content %}
    <h2>{{ resenha.title }}</h2>
    

    {% if resenha.image %}
        <img src="{{ resenha.image.url }}" width="200" alt="Capa do livro {{ resenha.title }}">
    {% else %}
        <p>A resenha não possui imagem/capa.</p> 
    {% endif %}
    

    <p>Autor da Resenha: {{ resenha.autor }} - Data de Publicação: {{ resenha.data_postagem|date:"d/m/Y" }}</p>
    
    <hr>
    
    <h3>Autor do Livro:</h3>
    <p>{{ resenha.autor_nome }}</p>
    
    
    <h3>Corpo da Resenha:</h3>
    <p>{{ resenha.resenha|safe }}</p>
    

    <h3>Categorias:</h3>
    <p>
        {% for category in resenha.categories.all %}
            <a href="{% url 'livros:category_detail' category.pk %}">{{ category.name }}</a>
            {% if not forloop.last %}, {% endif %}
        {% empty %}
            <p>Nenhuma categoria atribuída.</p>
        {% endfor %}
    </p>

    <hr>

    <a href="{% url 'livros:update' resenha.id %}">Editar resenha</a> |
    <a href="{% url 'livros:delete' resenha.id %}">Deletar resenha</a>

    <section>
        <header><h3>Comentários</h3></header>

        <a href="{% url 'livros:view_comments' resenha.id %}">
            <button>Ver comentários</button>
        </a>
    </section>
{% endblock content %}

Aplicação CRUD com Django/livros/templates/livros/resenha_list.html
{% extends 'base.html'%}
{% block content %}
    <h2>Resenhas de Livros</h2>
    <p>Aqui você encontrará as melhores resenhas de livros.</p>

    <section>
        <ul>
            <li> <a href="{% url 'livros:search' %}">Buscar resenha</a></li>
            <li><a href="{% url 'livros:create' %}">Adicionar nova resenha</a></li>
        </ul>
    </section>
    
    {% if category %}
        <h2>Resenhas na Categoria: {{ category.name }}</h2>
    {% else %}
        <h2>Todas as Resenhas</h2>
    {% endif %}

    {% if resenha_list %} 
    <section>
        {% for r in resenha_list %} 
        <article>
            <a href="{% url 'livros:detail' r.id %}">
                {{r.title}}
            </a>
        </article>
        {% endfor %}
    </section>
    {% else %}
    <p> Nenhuma resenha cadastrada.</p>
    {% endif %}
{% endblock content %}

Aplicação CRUD com Django/livros/templates/livros/search.html
{% extends 'base.html'%}

{% block content %}
<h2> Busca resenha pelo nome:</h2>
<form action="{% url 'livros:search' %}">
    <p>
        <label for="id_query">Título do Livro:</label>
        <input type="text" name="query" id="id_query"/>
    </p>
    <button type="submit">Buscar</button>
</form>

{% if resenha_list %}
    <h2> Resenhas encontradas:</h2>
    <section> 
        {% for resenha in resenha_list %}
        <article>
            {# Adicionando link para o detalhe #}
            <a href="{% url 'livros:detail' resenha.id %}">
                <p>{{ resenha.title }}</p>
            </a>
        </article>
        {% endfor %}
    </section>
{% else %}
    <p>Nenhuma resenha encontrada.</p>
{% endif %}
{% endblock content %}

Aplicação CRUD com Django/livros/templates/livros/update.html
{% extends 'base.html'%}

{% block content %}
<h2> Atualizar resenha "{{resenha.title}}"</h2>
<p> Capa/Imagem atual: {% if resenha.image %} {{resenha.image}} {% else %} Nenhuma {% endif %}</p>
<form method="post" enctype="multipart/form-data" action = "{% url 'livros:update' resenha.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar Resenha</button>
</form>
<a href="{% url 'livros:index' %}">Voltar para a lista</a>
{% endblock content %}