Aplicação CRUD com Django/livros/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'livros'

urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('<int:resenha_id>/', views.detail_resenha, name='detail'), 
    path('update/<int:resenha_id>/', views.update_resenha, name='update'), 
    path('delete/<int:resenha_id>/', views.delete_resenha, name='delete'), 
    path('search/', views.search_resenha, name='search'), 
    path('create/', views.create_resenha, name='create'), 
    path('<int:resenha_id>/createcomments/', views.create_comment, name='create_comment'), 
    path('<int:resenha_id>/comments/', views.view_comments, name='view_comments'), 
    
# Listagem de todas as categorias
    path('categories/', views.CategoryListView.as_view(), name='category_list'), 
    
    # Detalhe da categoria (lista posts da categoria)
    path('categories/<int:pk>/', views.category_detail, name='category_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Aplicação CRUD com Django/site_resenhas/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('livros/', include('livros.urls', namespace='livros')),
    path('', include('staticpages.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Aplicação CRUD com Django/staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

Aplicação CRUD com Django/staticpages/models.py
from django.db import models

# Create your models here.

Aplicação CRUD com Django/staticpages/views.py
from django.shortcuts import render

def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)
# Create your views here.

Aplicação CRUD com Django/staticpages/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock title %}|
    </title>
</head>

<body>
    <header id = "main-header">
        <h1 id = 'titulo_site'>Blog de resenhas de livros</h1>
        <nav id = "main-nav">
            <ul>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'livros:index' %}">Resenhas</a></li>
                <li><a href="{% url 'livros:category_list' %}">Categorias</a></li>
            </ul>
        </nav>
    </header>
    <main id = "main-content">
        {% block content %}
        {% endblock content%}
    </main>
    <footer id = "main-footer">
        <p>
            <small>© 2025</small>
        </p>
    </footer>
</body>


</html>